server:
  port: 8084
spring:
  application:
    name: quizService


  datasource:
    url: jdbc:h2:mem:quizDb     
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: update          
    database-platform: org.hibernate.dialect.H2Dialect

  # Enable H2 console
  h2:
    console:
      enabled: true
      path: /h2-console
  config:
      import: "optional:configserver:http://localhost:8088"
# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka


management:
  endpoints:
    web:
      exposure:
        include: health, info
  health:
    circuitbreakers:
      enabled: true
    # db:
    #   enabled: true  
    # diskspace:
    #   enabled: true 

  endpoint:
    health:
      show-details: always


        




resilience4j:
  circuitbreaker:
    instances:
      quizQuestionBreaker:
            register-health-indicator: true
            event-consumer-buffer-size: 10
            failure-rate-threshold: 50
            minimum-number-of-calls: 3
            automatic-transition-from-open-to-half-open-enabled: true
            wait-duration-in-open-state: 6s
            permitted-number-of-calls-in-half-open-state: 3
            sliding-window-size: 10
            sliding-window-type: count-based
  retry:
    instances:
      quizQuestionBreaker:
        max-attempts: 3
        wait-duration: 5s
  ratelimiter:
    instances:
      quizQuestionBreaker:
        timeout-duration: 0s
        limit-refresh-period: 4s
        limit-for-period: 2

