server:
  port: 8085

spring:
  application:
    name: questionservice

  datasource:
    url: jdbc:h2:mem:questionDb     
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: update          
    database-platform: org.hibernate.dialect.H2Dialect

  # Enable H2 console
  h2:
    console:
      enabled: true
      path: /h2-console


  config:
      import: "optional:configserver:http://localhost:8088"

# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka




