server:
  port: 8087
spring:
  application:
    name: apigateway

  cloud:
    gateway:
      routes:
        - id: quizService
          uri: lb://quizService
          predicates:
            - Path=/quiz/**
        - id: questionservice
          uri: lb://questionservice
          predicates:
            - Path=/question/**



  config:
      import: "optional:configserver:http://localhost:8088"
# eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  
